language: node_js
node_js:
  - 14.15.0
cache:
  directories:
    - node_modules
env:
  - secure:
      - bzsQ3//C5L0wJoXcb9ijyPKHRzvz85QtGQk2FgDVQoc3PdtNzBTYewzYUl92SHAH9T3p0n5B2+TinaKNtXpZw35FumOeSHDHGKfTFihoWkdUfKLynp144+INyaMxP2G6AcayjcT2BjeAbUQZSQyHk+VhOoj+SdcpXwWg0tdEQmIJG6Kkh4pKkgpsziSAJNZUaoL25wPbAVIPE0oDJLkmMLUr5mPWtdUpsw0Hsb5exIrjbFfxtg4HToLYxkI0RvAa70PXfk+LvDQmJSDjbsZS6ihhTviIkXv7yTRBe7/eUPWsyadx0N39e8isCzXycjcjcwYGZ0PI/F2yFytFAyBjOhMXRl5WXHwZLLQPX6H3NDRN4b9EQzMVREvlFyhFTBI52+oPiFcHuIV+5Cc0AaQzM7A7WbzHIxsTki7RAcZxFFtU/EicXahrLwIeScVHx3WdeOQh6DMXYv8pHMoMnzpVkQuSya5qo9BvKWdsZVO8J3TVbLBZd/k27EViwGgWXWp52n5gpf39aT98YOnaDCfUShcKk5f+07J8CpmeBXvwLpdKD8pNW/Ja66aeNjDl9TTsmJfVft1odTawYNTRROkhnYZBBI/yzl/EGmtn+PzYfVaO4UaXhd3mICz6cFvNtiHekg7mFleWWIi0fb4UQkZiF8qWFD+bjv+K50GccDqKM5g="GITHUB_ACCESS_TOKEN"
      - rap8cxmbXqukSIAPx2j1Ui3qOK4DCXJqw7RYdpdzw3KYysEmoS2jhxzPlEHyxCJ/6+7oTo+BWi4/SOhszWCYo+FGewIF5oL+OEVL9vW/tkEbbMjyazi0fp0YP33JFSrMJXM+vdsrRX2WjGItpp6Btj7C+740LK1rdGfioGJ0iwHfJf4zLkDHU/0jnbD1/aQA2LrYFgDVMAQPTjvu7fF3Fj87/bomR3iZ28/AZYj932+c/ghv1AwtG+HrijMAUcE9oMlTC1NWsOnlGR/N34NeDfrhq6RtJ8Ojirx7Ul9U2BaJMx3hkQz16D9Xsu1a7uNQHz11NHxoZUy4MBoOmfyuhkHiLZUdZIqz1QLta2qvlFqT6udNYQSeX2eTW3o3KkHyMknBn+Ob9Ze6u8+HxGvuwoUu0LGZj9Im+l57VdEO6/YzTIskVd6mac1WKMwtS5Cndke5CBwH4KRl+zKV/tRThg4dc+l6vm61y+BZcHtklUK8O9Dt32Ks/p/t7WIkwN1UBKDEKVM5v6udgcjvvoP8zEWQxAJ0RuSrz/pmu6E2JTG2D9OUdO0pp9Jc8/frO5CY1kpMGn56Or9mjrYCLwgKxLe90+Pls6b3b+Q751ScIitlggcB8No409VYEPiViY9+hTpiW1dIzPzoTK5QGSK1VDKJq4yV6F12AjKmT9Pf1sw="AZURE_MAIL_ENDPOINT_PROD"

before_script:
  - "echo 'ready to start building \U0001F44D'"
  - cd src/svelteComponents/github_repos_widget
  - npm ci
script:
  - "echo 'building svelte mini app \U0001F6E0️'"
  - npm run build
  - "echo 'generating service worker \U0001F9F0'"
  - cd ../../..
  - npm run generate:serviceworker
  - "echo 'building eleventy app \U0001F3D7️'"
  - npm run build
before_deploy:
  - "echo 'ready to deploy to netlify \U0001F680'"
  - npm install netlify-cli -g
deploy:
  provider: script
  edge: true
  script: netlify deploy --dir=dist --prod --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN
  on:
    branch: master
after_deploy:
  - echo 'Deployment complete'
